### ISSUE TITLE
Improve and clean up bootstrap folders

### ISSUE THREAD

**Issue by kimfy** [blinqas/station#27]
1. [x] Move bootstrapping from /tests/tfe/bootstrap to /bootstrap (PR #31)
2. [x] Make it dynamic, remove static references (PR #29)
3. [x] Delete all but /tests/tfe/bootstrap (/bootstrap) (PR #31)

**Comment by kimfy** [comment]
Resolved in #31
