### ISSUE TITLE
Improve type constraints of input variables

### ISSUE THREAD

**Issue by kimfy** [blinqas/station#39]
Station can be hard to work with for newcomers because of its bad type constraint set up.

Improve all variables:
- [x] `resource_groups`: #51 
- [x] `federated_identity_credential_config`: #52
- [x] `applications`: #48 
- [x] `groups`: #49 
- [x] `user_assigned_identities` #57 
- [x] `tfe`: Resolved in PR #36
